import json
import os

HISTORY_PATH = 'history.json'

def main():
    if not os.path.exists(HISTORY_PATH):
        return

    with open(HISTORY_PATH, 'r', encoding='utf-8') as f:
        history = json.load(f)

    print("🔧 Fixing suspicious outcomes for today...")
    
    # Games to reset (those with 3-3, 2-2 generated by random logic previously)
    # Or just reset ALL 'PENDING' games for today to 0-0 if they are not confirmed?
    # Actually, we should look for specific fake scores from the random generator.
    
    count = 0
    for h in history:
        if h.get('date') == "11/02":
            # Check for suspicious draw scores that are statistically rare for placeholders
            if h.get('score') in ["3-3", "2-2"] and h.get('status') == "PENDING":
                 print(f"Resetting {h['home']} ({h['score']}) -> 0-0 PENDING")
                 h['score'] = "0-0"
                 h['status'] = "PENDING"
                 h['profit'] = "0%"
                 count += 1
            elif h.get('home') == "Atlético-MG" and h.get('score') == "3-3":
                 h['score'] = "0-0"
                 h['status'] = "PENDING"
                 count += 1
            elif h.get('home') == "Chapecoense" and h.get('score') == "3-3":
                 h['score'] = "0-0"
                 h['status'] = "PENDING"
                 count += 1
    
    if count > 0:
        with open(HISTORY_PATH, 'w', encoding='utf-8') as f:
            json.dump(history, f, indent=4, ensure_ascii=False)
        print(f"✅ Fixed {count} entries.")
    else:
        print("✅ No suspicious entries found.")

if __name__ == "__main__":
    main()
